"""Application configuration."""

from pathlib import Path

BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "data"
VOCAB_DIR = DATA_DIR / "vocab"
DB_PATH = DATA_DIR / "flashcard.db"
SETTINGS_PATH = DATA_DIR / "user_settings.json"
VOCAB_SOURCE = VOCAB_DIR / "vocab_source.csv"

DATA_DIR.mkdir(exist_ok=True)
VOCAB_DIR.mkdir(exist_ok=True)

MIN_WORDS_REQUIRED = 1000

DEFAULT_WINDOW_WIDTH = 1920
DEFAULT_WINDOW_HEIGHT = 1080
MIN_WINDOW_WIDTH = 640
MIN_WINDOW_HEIGHT = 480
MAX_WINDOW_WIDTH = 1920
MAX_WINDOW_HEIGHT = 1080

DEFAULT_QUESTION_COUNT = 20
MIN_QUESTION_COUNT = 10
MAX_QUESTION_COUNT = 100

DEFAULT_TIME_LIMIT = 300
MIN_TIME_LIMIT = 60
MAX_TIME_LIMIT = 600

MIN_DIFFICULTY = 1
MAX_DIFFICULTY = 5
DEFAULT_DIFFICULTY = 3
